### ISSUE TITLE
Doesn't compile under Flex Framework 4.5.1

### ISSUE THREAD

**Issue by artman** [artman/Flow#1]
Currently Flow throws up a number of errors when trying to compile it under 4.5.1.

**Comment by artman** [comment]
Any idea Kaitsu, why this it does what it does under Flex 4.5.1 and how to fix it?

**Comment by kaihannonen** [comment]
Hmm, we're using 4.5.1 and it compiles. Are you targeting flash player 10 (-swf-version=12)?

**Comment by artman** [comment]
Um, yeah, the Lib compiles, but using it in a Flex 4.5.1 Framework project will either get you compile-time errors or runtime errors. It has something to do with how mx.states.\* is included in a different order with 4.5.1 tha 4.5.0. If you include the libs src-folder in your target project you can get rid of these problems, but one should be able to use it by just deagging the swc into a project's lib-folder.

**Comment by artman** [comment]
It compiles perfectly againsta Flex 4.6. Closing issue as next release of Flow will target 4.6
