### ISSUE TITLE
Disabled Button's initial skin state is wrong

### ISSUE THREAD

**Issue by yolque** [artman/Flow#4]
<fw:Button disabled="true"/> doesn't seem to change the skinState to "disabled" initially; works if you disable the button later.

**Comment by artman** [comment]
Yeah, I'm on this. Need to fix this for one of my projects...

**Comment by artman** [comment]
States are added after the component tries to set them. Fixed.

**Comment by artman** [comment]
States are added after the component tries to set them. Fixed.
