### ISSUE TITLE
Upgrade List

### ISSUE THREAD

**Issue by shamruk** [artman/Flow#7]
It would be great to have:
- not recreating all views when collection is changed (for e.g. by CollectionEventKind.ADD) !
- reuse old (removed) itemRenderers instead of creating new ones
- itemRendererFunction support
- virtual layout support

See spark:DataGroup:dataProvider_collectionChangeHandler
See https://github.com/shamruk/Mulunka/blob/master/src/mulunka/display/CollectionView.as

**Comment by artman** [comment]
Definitely agree. Want to give it a go and submit a pull request?

**Comment by shamruk** [comment]
I am busy finishing current project (on flex). I hope that I will find some time to handle some points in a while.

I think there should be "DataContainer" (like spark:DataGroup) between Container and List (list has selection).

PS
The project is amazing!
